spring.application.name=GestionePizzeriaJPA

spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver
spring.datasource.url= jdbc:mysql://localhost:3306/pomig001_spring_pizzeria_jpa
spring.datasource.username= root
spring.datasource.password= root
spring.jpa.hibernate.ddl-auto= update
spring.jpa.hibernate.dialect= org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.default_schema= public
